### ISSUE TITLE
 Add logic when `current.value` is undefined 

### ISSUE THREAD

**Issue by yuriko627** [cryptoeconomicslab/WakkanayBrowserWallet#100]
the case when `current.value` is undefined (empty) should be considered.

_Originally posted by @tkmct in https://github.com/cryptoeconomicslab/WakkanayBrowserWallet/pull/96_

**Comment by yuriko627** [comment]
now it is rendered 0, not NaN anymore. How does that sound?

**Comment by tkmct** [comment]
good
